version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      # - /backend/node_modules:/app/node_modules


  # mongo:
  #   image: mongo:3.4
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db
  

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongo
