apiVersion: v1
kind: ConfigMap
metadata:
  name: question-service-config-dev
  namespace: development
data:
  PORT: "8084"
  MONGODB_URI: "mongodb+srv://deon:1nTkXq4RddJdExVt@cluster0.vzwsoob.mongodb.net/?retryWrites=true&w=majority"
