apiVersion: v1
kind: Service
metadata:
    name: collaboration-service
    namespace: development
spec:
    selector:
        app: collaboration-serivce
    ports:
        - name: "collaboration-serivce-port"
          port: 3001
          targetPort: 3000
    type: NodePort
status:
    loadBalancer: {}