apiVersion: v1
kind: Service
metadata:
    name: frontend-dev
    namespace: development
spec:
    selector:
        app: frontend
    ports:
        - protocol: TCP
          name: "frontend-port"
          port: 3000
          targetPort: 3000
    type: LoadBalancer
status:
    loadBalancer: {}