apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: development
spec:
    selector:
        app: frontend
    ports:
        - name: "frontend-port"
          port: 3000
          targetPort: 3000
    type: NodePort
status:
    loadBalancer: {}