apiVersion: v1
kind: Service
metadata:
    name: question-service
    namespace: development
spec:
    selector:
        app: question-serivce
    ports:
        - name: "question-serivce-port"
          port: 8084
          targetPort: 8084
    type: NodePort
status:
    loadBalancer: {}