apiVersion: v1
kind: Service
metadata:
    name: collaboration-service-dev
    namespace: development
spec:
    selector:
        app: collaboration-serivce
    ports:
        - name: "collaboration-serivce-port"
          port: 3000
          targetPort: 3001
    type: NodePort
status:
    loadBalancer: {}