apiVersion: v1
kind: Service
metadata:
    name: matching-service-dev
    namespace: development
spec:
    selector:
        app: matching-serivce
    ports:
        - name: "matching-serivce-port"
          port: 8081
          targetPort: 8081
    type: NodePort
status:
    loadBalancer: {}