apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service-deployment-dev
  namespace: development
spec:
    replicas: 1
    selector:
      matchLabels:
        app: collaboration-service
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    template:
      metadata:
        labels:
          app: collaboration-service
      spec:
        containers:
        - image: wxy1203/3219assignment-collaboration-service:v2
          name: collaboration-service-container
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "3Gi" # Request 3GB of memory
              cpu: "700m" # Request 0.7 CPU
            limits:
              memory: "4Gi" # Limit memory to 4GB
              cpu: "1000m" # Limit CPU to 1 CPU
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: collaboration-service-config-dev
                  key: BASE_URL
            - name: LIVEBLOCKS_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: collaboration-service-config-dev
                  key: LIVEBLOCKS_PUBLIC_KEY
            - name: LIVEBLOCKS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: collaboration-service-config-dev
                  key: LIVEBLOCKS_SECRET_KEY
            - name: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: collaboration-service-config-dev
                  key: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY

status: {} # Empty status section