apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-dev
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: wxy1203/3219assignment-frontend:v2
        name: frontend-container
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "150Mi" # Request 150MB of memory
            cpu: "100m" # Request 0.1 CPU
          limits:
            memory: "200Mi" # Limit memory to 200MB
            cpu: "200m" # Limit CPU to 0.2 CPU
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: PORT
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: NODE_ENV
          - name: BASE_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: BASE_URL
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: DATABASE_URL
          - name: NEXTAUTH_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: NEXTAUTH_URL
          - name: NEXTAUTH_SECRET
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: NEXTAUTH_SECRET
          - name: GITHUB_ID
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: GITHUB_ID
          - name: GITHUB_SECRET
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: GITHUB_SECRET
          - name: LIVEBLOCKS_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: LIVEBLOCKS_PUBLIC_KEY
          - name: LIVEBLOCKS_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: LIVEBLOCKS_SECRET_KEY
          - name: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY
          - name: DISCORD_ID
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: DISCORD_ID
          - name: DISCORD_SECRET
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: DISCORD_SECRET
          - name: OPENAI_API_KEY
            valueFrom:
              configMapKeyRef:
                name: frontend-config-dev
                key: OPENAI_API_KEY
 

status: {} # Empty status section